<x-tallkit-button
    type="submit"
    :text="$text"
    :active="$active"
    :click="$click"
    :wire-click="$wireClick"
    :icon="$icon"
    :icon-left="$iconLeft"
    :icon-right="$iconRight"
    :color="$color"
    :rounded="$rounded"
    :shadow="$shadow"
    :outlined="$outlined"
    :link-text="$linkText"
    :bordered="$bordered"
    :loading="$loading ?? true"
    :preset="$preset"
    :tooltip="$tooltip"
    :attributes="$attributes"
    :props="$props()"
    :theme="$theme"
>{{ $slot }}</x-tallkit-button>
