<x-tallkit-button
    :attributes="$attributes"
    :text="$text"
    :active="$active"
    :href="$href ?? url()->previous()"
    :route="$route"
    :target="$target"
    :click="$click"
    :wire-click="$wireClick"
    :icon="$icon"
    :icon-left="$iconLeft"
    :icon-right="$iconRight"
    :color="$color"
    :rounded="$rounded"
    :shadow="$shadow"
    :outlined="$outlined"
    :link-text="$linkText"
    :bordered="$bordered"
    :loading="$loading"
    :preset="$preset ?? 'back'"
    :tooltip="$tooltip"
    :props="$props"
    :theme="$theme"
>{{ $slot }}</x-tallkit-button>
